# Generated by Django 5.2.7 on 2025-10-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="background_color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="section",
            name="background_gradient",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="section",
            name="background_image",
            field=models.ImageField(blank=True, null=True, upload_to="backgrounds/"),
        ),
        migrations.AddField(
            model_name="section",
            name="border_radius",
            field=models.CharField(blank=True, default="0", max_length=20),
        ),
        migrations.AddField(
            model_name="section",
            name="button_color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="section",
            name="button_link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="section",
            name="button_text",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="section",
            name="button_text_color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="section",
            name="font_family",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="section",
            name="font_size",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="section",
            name="margin",
            field=models.CharField(blank=True, default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="section",
            name="padding",
            field=models.CharField(blank=True, default="60px 0", max_length=50),
        ),
        migrations.AddField(
            model_name="section",
            name="template_type",
            field=models.CharField(blank=True, default="custom", max_length=50),
        ),
        migrations.AddField(
            model_name="section",
            name="text_color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
