# Generated by Django 5.2.6 on 2025-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="theme",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
